server:
  port: 8088

spring:
  application:
    name: config-service
    profiles:
      active: native

    cloud:
      config:
        server:
          native:
            search-locations: file:///Users/apple/Desktop/microservice_demo/config-service/src/main/resources/config



